### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lantis1008** [lantis1008/gargoyle-plugin-adblock#1]
TODO:
- [x] Rework plugin to put all files onto /plugin_root which means it will go onto the USB drive if selected by the user.
- [x] Remove legacy web server support. Plugin now only compatible >= Gargoyle 1.9.0
- [x] Make GUI for viewing block, black and white lists
- [x] Block list is now searchable from the GUI
- [x] easy way of moving items from block to white list
- [x] easy way to delete items from white and black lists
- [x] write black and white lists back to router
- [ ] better Tor workaround, probably by using the built in force_router_dns function from Gargoyle
- [ ] better exemption list? GUI?
- [ ] at the very least, a warning that exempting users also requires them to change their DNS server

REMOVED:
- Wireless clients only mode has been removed. Gargoyle bridges wifi and lan interfaces and so this rule never worked correctly in the first place. If someone can come up with a better solution, I will consider re-adding it.

**Comment by stopspazzing** [comment]
https://jsfiddle.net/StopSpazzing/4kd8aeq5/

Working whitelist box. When I try to add a black list box, jsfiddle doesnt like it even tho runs fine on chrome in a html file.

https://gist.github.com/stopspazzing/874a69f18f7c7326d8e0
This is the working html file with both. Transfer hasnt be finished yet

**Comment by stopspazzing** [comment]
Finished the transfer code. Works well enough. Fixed weird issue.

**Comment by lantis1008** [comment]
@stopspazzing
Hi mate I've finally started working on this stuff. 

JavaScript is getting upset that I'm trying to push >10000 lines into an array. Exceeds a limit apparently lol. 

Any ideas? Some people suggest using a POST method to do it which has no limit but I'm honestly not familiar with it.

**Comment by lantis1008** [comment]
Worked around it so never mind. 
Big GUI changes coming @Teffalump which you may be interested in! Stay tuned.

**Comment by stopspazzing** [comment]
Sorry man, been crazy busy. I'm glad to see it's finally being worked on and looking forward to seeing the update.

**Comment by teffalump** [comment]
@lantis1008: I'm looking forward to it. =-) I need to push people over to @dibdot and yours packages. =-)

**Comment by lantis1008** [comment]
I would really appreciate the help of @obsy and @cappiewu to translate the new files into Polish and Chinese.
Thank you in advance.

Line 16 onwards is new.
https://github.com/lantis1008/gargoyle-plugin-adblock/blob/master/i18n%20support%20files/plugin-gargoyle-i18n-English-EN/files/www/i18n/English-EN/ablock.js
